### ISSUE TITLE
Question: Requirements for Windows

### ISSUE THREAD

**Issue by foxriver76** [alastairpatrick/nopy#5]
Hello,

what are the requirements for using npip on windows. In my tests it fails on Windows with:

```
npip install
No python_modules directory; installing pip locally if needed.
Error: spawn python3 ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I'm installing Python 3.6 in my test and setting it to the path. Example run:
https://ci.appveyor.com/project/foxriver76/iobroker-xbox/build/job/m2p9ypywewsaxm49

It would be great if you would provide me some help on this.

**Comment by foxriver76** [comment]
The problem seems to be that I want to execute with python3, but on windows it willbe named python and not python3. Is there a possibility like try & catch to try it with python3 else use python?

**Comment by foxriver76** [comment]
Or just like a fallback in bash 
```bash
python3 doThis || python doThis
```

**Comment by alastairpatrick** [comment]
I expect the path to the python interpreter has been set to "python3" in package.json:
`"python": { "execPath": "python3" },`

Probably "python3" isn't found because it isn't in the path, which could be the case for some python distributions. On Windows, I use the [ActiveState python distribution](https://www.activestate.com/activepython), which seems to work.

Which python distribution are you using?

**Comment by foxriver76** [comment]
Yes, thats correct.. otherwise on most linux systems it will install my dependencies with python2.7 but my deps require python3. Maybe in some distributions it will work with python3 on windows too. But what if I want to provide a npm package? I can't hope that it will work with python3 on the users system. 

I didn't test it with any other python distribution on windows. Only in my continuous integration tool, the windows build fails when execPath is python3 and passes with python.

**Comment by alastairpatrick** [comment]
Windows CPython seems to have unique way of selecting which version of python to use, called the [Python Launcher](https://docs.python.org/3/using/windows.html). I don't have a Windows box on which I can install CPython at the moment. What happens if you set "execPath" to "py" rather than "python3"? I believe it will respect the version of python specified in the shebang, so you could mess with that as well.

Obviously this will not work for Linux, Max, ActiveState, etc. My idea is, the python version could be specified in "package.json" and then on each platform it would attempt various ways of running that version of python.

For example, to launch python 3 on Windows it might try:
python3
py -3
python

Or on Linux:
python3
python

**Comment by foxriver76** [comment]
Yes, the problem is that py would not run on Linux, Mac. So it would be a cool feature for your module to configure something like alternative versions. E.g.  sepcifing the execPath as an Array, so in the below scenario if python3 fails using python
```json
"python": {
  	"execPath": [
            "python3",
            "python"
        ],
  	"path": ["."],
    "dependencies": {
      "xbox-smartglass-rest": "",
      "xbox-smartglass-core": ""
}
```

What are your thoughts on this?

**Comment by alastairpatrick** [comment]
That seems like reasonable thing to do. If you want to try it, in api.js, I'd change getPythonInfo() so it accepts either a string or array for the pythonExecPath argument. Than try each path in turn until it found one that worked and return the path to the working one. Then the caller, pythonEnv() would use the returned path to set NOPY_PYTHON_EXEC_PATH.

**Comment by alastairpatrick** [comment]
I realized I don't need to install CPython on a Windows box to test your idea so I just did it. Let me know if it solves the problem and I'll publish it,

**Comment by foxriver76** [comment]
You're awesome, that works :1st_place_medal:  
Thank you. :)
